---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-1
  labels:
    fake-1: "yea"
data:
  test-fake-1: |-
     This is test fake 1 data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-2
  labels:
    some-label: "somevalue"
data:
  test-fake-2: |-
     This is test fake 2 data

# @kopf.on.event(
#     "",
#     "v1",
#     "configmaps",
#     labels={"some-label": "somevalue"},
# )
